import type { FieldConfig, ModuleConfig } from "../../types";

const statusField: FieldConfig = {
  key: "status",
  label: "Status",
  type: "select",
  required: true,
  options: ["Active", "Pending", "Pending Approval", "Approved", "Posted", "Ready", "Delivered", "Attention", "Normal", "Inactive"]
};

const commonText = (key: string, label: string, required = true): FieldConfig => ({ key, label, type: "text", required });
const money = (key: string, label: string): FieldConfig => ({ key, label, type: "number", required: true });
const date = (key: string, label: string): FieldConfig => ({ key, label, type: "date", required: true });

export const moduleConfigs: ModuleConfig[] = [
  {
    key: "users",
    title: "User Management",
    subtitle: "Create users, assign roles, activate/deactivate accounts and review access ownership.",
    entityName: "User",
    route: "/app/users",
    endpoint: "/api/users",
    permission: "users",
    fields: [
      commonText("name", "Full Name"),
      commonText("email", "Email"),
      { key: "role", label: "Role", type: "select", required: true, options: ["Super Admin", "Managing Director", "Accounts", "Import Officer", "Warehouse Manager", "Sales Manager", "Sales Executive"] },
      commonText("title", "Job Title"),
      commonText("department", "Department"),
      commonText("phone", "Phone"),
      statusField
    ],
    tableColumns: ["name", "email", "role", "department", "status"],
    searchable: ["name", "email", "role", "department"],
    filterKey: "role",
    statusKey: "status",
    descriptionKey: "email"
  },
  {
    key: "companies",
    title: "Companies & Branches",
    subtitle: "Company profile, branches, sales offices and operating entities.",
    entityName: "Company",
    route: "/app/master/companies",
    endpoint: "/api/companies",
    permission: "master-data",
    fields: [commonText("companyName", "Company Name"), commonText("branch", "Branch"), commonText("phone", "Phone"), statusField],
    tableColumns: ["companyName", "branch", "phone", "status"],
    searchable: ["companyName", "branch", "phone"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "branch"
  },
  {
    key: "warehouses",
    title: "Warehouse Master",
    subtitle: "Warehouse locations, capacities and active operating status.",
    entityName: "Warehouse",
    route: "/app/master/warehouses",
    endpoint: "/api/warehouses",
    permission: "master-data",
    fields: [commonText("warehouseName", "Warehouse Name"), commonText("location", "Location"), commonText("capacity", "Capacity"), statusField],
    tableColumns: ["warehouseName", "location", "capacity", "status"],
    searchable: ["warehouseName", "location"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "location"
  },
  {
    key: "bin-locations",
    title: "BIN Location Management",
    subtitle: "BIN location, zone and warehouse capacity controls.",
    entityName: "BIN Location",
    route: "/app/warehouse/bin-locations",
    endpoint: "/api/bin-locations",
    permission: "warehouse",
    fields: [commonText("warehouse", "Warehouse"), commonText("binCode", "BIN Code"), commonText("zone", "Zone"), { ...statusField, options: ["Available", "Reserved", "Hold", "Inactive"] }],
    tableColumns: ["warehouse", "binCode", "zone", "status"],
    searchable: ["warehouse", "binCode", "zone"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "zone"
  },
  {
    key: "products",
    title: "Products / SKUs",
    subtitle: "Medical device SKU master with images, device type, prices, reorder levels and active status.",
    entityName: "Product",
    route: "/app/products",
    endpoint: "/api/products",
    permission: "products",
    fields: [
      commonText("productCode", "Product Code"),
      commonText("productName", "Product Name"),
      { key: "category", label: "Category", type: "select", required: true, options: ["Hemodialysis", "Dialysis Consumable", "Dialysis Access", "Infusion", "Urology", "Respiratory"] },
      commonText("unit", "Unit"),
      commonText("brand", "Brand"),
      commonText("manufacturer", "Manufacturer"),
      commonText("deviceType", "Medical Device Type"),
      money("purchasePrice", "Purchase Price"),
      money("salesPrice", "Sales Price"),
      money("reorderLevel", "Reorder Level"),
      { key: "description", label: "Description", type: "textarea", required: true },
      commonText("imageUrl", "Demo Image URL", false),
      statusField
    ],
    tableColumns: ["productCode", "productName", "category", "unit", "purchasePrice", "salesPrice", "status"],
    searchable: ["productCode", "productName", "category", "manufacturer"],
    filterKey: "category",
    statusKey: "status",
    descriptionKey: "description"
  },
  {
    key: "suppliers",
    title: "Supplier Database",
    subtitle: "Overseas suppliers, C&F agents, contact persons, payment terms and performance scores.",
    entityName: "Supplier",
    route: "/app/suppliers",
    endpoint: "/api/suppliers",
    permission: "suppliers",
    fields: [commonText("companyName", "Company Name"), commonText("country", "Country"), commonText("contactPerson", "Contact Person"), commonText("productCategory", "Product Category"), commonText("paymentTerms", "Payment Terms"), money("rating", "Rating"), statusField],
    tableColumns: ["companyName", "country", "contactPerson", "productCategory", "paymentTerms", "rating", "status"],
    searchable: ["companyName", "country", "contactPerson", "productCategory"],
    filterKey: "country",
    statusKey: "status",
    descriptionKey: "paymentTerms"
  },
  {
    key: "customers",
    title: "Customer & CRM Master",
    subtitle: "Hospitals, clinics, dealers and pharmacies with credit limit, territory and sales ownership.",
    entityName: "Customer",
    route: "/app/customers",
    endpoint: "/api/customers",
    permission: "customers",
    fields: [
      commonText("customerName", "Customer Name"),
      { key: "type", label: "Type", type: "select", required: true, options: ["Hospital", "Clinic", "Dealer", "Pharmacy"] },
      commonText("territory", "Territory"),
      commonText("contactPerson", "Contact Person"),
      commonText("phone", "Phone"),
      commonText("email", "Email", false),
      { key: "address", label: "Address", type: "textarea", required: true },
      money("creditLimit", "Credit Limit"),
      money("openingDue", "Opening Due"),
      commonText("assignedSalesExecutive", "Assigned Sales Executive"),
      statusField
    ],
    tableColumns: ["customerName", "type", "territory", "assignedSalesExecutive", "creditLimit", "openingDue", "status"],
    searchable: ["customerName", "type", "territory", "assignedSalesExecutive"],
    filterKey: "type",
    statusKey: "status",
    descriptionKey: "address"
  },
  {
    key: "supplier-inquiries",
    title: "Supplier Inquiry",
    subtitle: "Inquiry pipeline before PI approval and purchase order generation.",
    entityName: "Inquiry",
    route: "/app/procurement/inquiries",
    endpoint: "/api/supplier-inquiries",
    permission: "procurement",
    fields: [commonText("inquiryNo", "Inquiry No"), commonText("supplier", "Supplier"), commonText("product", "Product"), money("requestedQty", "Requested Qty"), money("targetPrice", "Target Price"), { ...statusField, options: ["Pending", "Quoted", "Negotiation", "Closed"] }],
    tableColumns: ["inquiryNo", "supplier", "product", "requestedQty", "targetPrice", "status"],
    searchable: ["inquiryNo", "supplier", "product"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "supplier"
  },
  {
    key: "purchase-orders",
    title: "Purchase Orders",
    subtitle: "PO creation, approval, ordered quantity, currency, exchange rate and value tracking.",
    entityName: "Purchase Order",
    route: "/app/procurement/purchase-orders",
    endpoint: "/api/purchase-orders",
    permission: "procurement",
    fields: [commonText("poNumber", "PO Number"), commonText("supplier", "Supplier"), date("date", "PO Date"), commonText("product", "Products"), money("quantity", "Quantity"), commonText("currency", "Currency"), money("exchangeRate", "Exchange Rate"), money("totalValue", "Total Value"), { ...statusField, options: ["Draft", "Pending Approval", "Approved", "Ordered", "Partially Received", "Closed", "Cancelled"] }],
    tableColumns: ["poNumber", "supplier", "date", "product", "quantity", "currency", "totalValue", "status"],
    searchable: ["poNumber", "supplier", "product", "status"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "product",
    printTemplate: "purchase-order"
  },
  {
    key: "proforma-invoices",
    title: "PI Management",
    subtitle: "Proforma invoice approval, supplier amount and MD workflow.",
    entityName: "PI",
    route: "/app/import/pi",
    endpoint: "/api/proforma-invoices",
    permission: "import",
    fields: [commonText("piNumber", "PI Number"), commonText("supplier", "Supplier"), commonText("product", "Product"), money("amount", "Amount"), commonText("currency", "Currency"), commonText("approvalOwner", "Approval Owner"), { ...statusField, options: ["Draft", "Pending Approval", "Approved", "Rejected"] }],
    tableColumns: ["piNumber", "supplier", "product", "amount", "currency", "approvalOwner", "status"],
    searchable: ["piNumber", "supplier", "product"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "supplier"
  },
  {
    key: "lc-records",
    title: "LC Management",
    subtitle: "Letter of credit bank, expiry date, shipment date and amount control.",
    entityName: "LC",
    route: "/app/import/lc",
    endpoint: "/api/lc-records",
    permission: "import",
    fields: [commonText("lcNumber", "LC Number"), commonText("bank", "Bank"), commonText("supplier", "Supplier"), money("amount", "Amount"), date("expiryDate", "Expiry Date"), date("shipmentDate", "Shipment Date"), { ...statusField, options: ["Draft", "Open", "Expired", "Closed"] }],
    tableColumns: ["lcNumber", "bank", "supplier", "amount", "expiryDate", "shipmentDate", "status"],
    searchable: ["lcNumber", "bank", "supplier"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "supplier"
  },
  {
    key: "tt-payments",
    title: "TT Payment Management",
    subtitle: "TT payment requests, Swift copy mock upload and supplier payment status.",
    entityName: "TT Payment",
    route: "/app/import/tt",
    endpoint: "/api/tt-payments",
    permission: "import",
    fields: [commonText("ttNumber", "TT Number"), commonText("supplier", "Supplier"), money("amount", "Amount"), commonText("swiftCopy", "Swift Copy File"), { ...statusField, options: ["Draft", "Pending Approval", "Sent", "Rejected"] }],
    tableColumns: ["ttNumber", "supplier", "amount", "swiftCopy", "status"],
    searchable: ["ttNumber", "supplier", "swiftCopy"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "supplier"
  },
  {
    key: "shipments",
    title: "Shipment Management",
    subtitle: "BL, container, vessel, ETD, ETA, supplier and shipment status tracking.",
    entityName: "Shipment",
    route: "/app/import/shipments",
    endpoint: "/api/shipments",
    permission: "shipments",
    fields: [commonText("blNumber", "BL Number"), commonText("containerNumber", "Container Number"), commonText("vesselName", "Vessel Name"), date("etd", "ETD"), date("eta", "ETA"), commonText("supplier", "Supplier"), commonText("poReference", "PO Reference"), { ...statusField, options: ["Preparing", "Shipped", "Arrived Port", "Customs", "Cleared", "Warehouse Received"] }],
    tableColumns: ["blNumber", "containerNumber", "vesselName", "eta", "supplier", "poReference", "status"],
    searchable: ["blNumber", "containerNumber", "vesselName", "supplier", "poReference"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "supplier"
  },
  {
    key: "customs-landed-cost",
    title: "Customs & Landed Cost",
    subtitle: "Duty, VAT, AIT, freight, C&F, transport and per-unit landed-cost allocation preview.",
    entityName: "Landed Cost",
    route: "/app/customs/landed-cost",
    endpoint: "/api/customs/landed-cost",
    permission: "customs",
    fields: [commonText("poNumber", "PO Number"), commonText("consignmentNumber", "Consignment No"), commonText("lcTtNumber", "LC/TT Number"), commonText("productName", "Product Name"), commonText("productCode", "Product Code"), money("purchaseUnitFob", "FOB/U"), money("seaFreightUnit", "Sea Freight/U"), money("customsDutyUnit", "Duty/U"), money("cfCostUnit", "C&F/U"), money("localTransportUnit", "Transport/U"), money("bankLcInsuranceUnit", "Bank LC & Insurance/U"), money("totalLandedUnit", "Total Landed/U"), money("marginPreview", "Margin Preview %"), { ...statusField, options: ["Draft", "Pending Approval", "Approved", "Rejected"] }],
    tableColumns: ["poNumber", "consignmentNumber", "productName", "productCode", "totalLandedUnit", "marginPreview", "status"],
    searchable: ["poNumber", "consignmentNumber", "productName", "productCode"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "productName",
    printTemplate: "report"
  },
  {
    key: "grn",
    title: "Goods Receiving Notes",
    subtitle: "GRN receiving, rejected stock, batch, LOT, expiry and BIN location assignment.",
    entityName: "GRN",
    route: "/app/warehouse/grn",
    endpoint: "/api/grn",
    permission: "warehouse",
    fields: [commonText("grnNumber", "GRN Number"), commonText("supplier", "Supplier"), commonText("containerReference", "Container Reference"), commonText("product", "Product"), money("receivedQuantity", "Received Qty"), money("rejectedQuantity", "Rejected Qty"), commonText("batchNumber", "Batch Number"), commonText("lotNumber", "LOT Number"), date("expiryDate", "Expiry Date"), commonText("binLocation", "BIN Location"), commonText("warehouse", "Warehouse"), commonText("receivedBy", "Received By"), date("receivedDate", "Received Date"), { ...statusField, options: ["Draft", "Posted", "Rejected", "Hold"] }],
    tableColumns: ["grnNumber", "supplier", "containerReference", "product", "receivedQuantity", "rejectedQuantity", "binLocation", "status"],
    searchable: ["grnNumber", "supplier", "containerReference", "product", "batchNumber"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "product",
    printTemplate: "grn"
  },
  {
    key: "inventory-stock",
    title: "Real-Time Stock",
    subtitle: "Stock in hand, landed cost, valuation and warehouse availability.",
    entityName: "Stock Item",
    route: "/app/inventory/stock",
    endpoint: "/api/inventory/stock",
    permission: "inventory",
    fields: [commonText("productCode", "Product Code"), commonText("productName", "Product Name"), money("totalReceivedQty", "Received Qty"), money("totalSoldQty", "Sold Qty"), money("currentStockInHand", "Current Stock"), money("unitLandedCost", "Unit Landed Cost"), money("totalStockAssetValue", "Asset Value"), commonText("warehouse", "Warehouse"), { ...statusField, options: ["Normal", "Low Stock", "Hold", "Expired"] }],
    tableColumns: ["productCode", "productName", "currentStockInHand", "unitLandedCost", "totalStockAssetValue", "warehouse", "status"],
    searchable: ["productCode", "productName", "warehouse"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "warehouse"
  },
  {
    key: "inventory-batches",
    title: "Batch / LOT Tracking",
    subtitle: "Batch recall traceability, LOT tracking, FEFO rank and expiry alert windows.",
    entityName: "Batch",
    route: "/app/inventory/batches",
    endpoint: "/api/inventory/batches",
    permission: "inventory",
    fields: [commonText("product", "Product"), commonText("batchNumber", "Batch Number"), commonText("lotNumber", "LOT Number"), date("expiryDate", "Expiry Date"), commonText("binLocation", "BIN Location"), money("quantity", "Quantity"), money("fefoRank", "FEFO Rank"), { ...statusField, options: ["Normal", "6 Month Alert", "3 Month Alert", "1 Month Alert", "Expired"] }],
    tableColumns: ["product", "batchNumber", "lotNumber", "expiryDate", "binLocation", "quantity", "fefoRank", "status"],
    searchable: ["product", "batchNumber", "lotNumber", "binLocation"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "batchNumber"
  },
  {
    key: "inventory-movements",
    title: "Stock Movement Ledger",
    subtitle: "Stock in, stock out, transfer, adjustment, sale and return movement ledger.",
    entityName: "Movement",
    route: "/app/inventory/movements",
    endpoint: "/api/inventory/movements",
    permission: "inventory",
    fields: [date("date", "Date"), commonText("product", "Product"), commonText("batchNumber", "Batch Number"), { key: "movementType", label: "Movement Type", type: "select", required: true, options: ["Stock In", "Stock Out", "Transfer", "Adjustment", "Sale", "Return"] }, money("quantity", "Quantity"), commonText("reference", "Reference"), commonText("warehouseUser", "Warehouse User"), { ...statusField, options: ["Draft", "Posted", "Cancelled"] }],
    tableColumns: ["date", "product", "batchNumber", "movementType", "quantity", "reference", "status"],
    searchable: ["product", "batchNumber", "movementType", "reference"],
    filterKey: "movementType",
    statusKey: "status",
    descriptionKey: "reference"
  },
  {
    key: "inventory-physical-counts",
    title: "Physical Count & Variance",
    subtitle: "Physical stock count, system quantity comparison, variance approval and adjustment readiness.",
    entityName: "Physical Count",
    route: "/app/inventory/physical-counts",
    endpoint: "/api/inventory/physical-counts",
    permission: "inventory",
    fields: [commonText("countNo", "Count No"), commonText("warehouse", "Warehouse"), commonText("product", "Product"), commonText("batchNumber", "Batch Number"), money("systemQty", "System Qty"), money("countedQty", "Counted Qty"), money("varianceQty", "Variance Qty"), commonText("countedBy", "Counted By"), date("countDate", "Count Date"), { ...statusField, options: ["Draft", "Pending Approval", "Approved", "Posted", "Rejected"] }],
    tableColumns: ["countNo", "warehouse", "product", "batchNumber", "systemQty", "countedQty", "varianceQty", "status"],
    searchable: ["countNo", "warehouse", "product", "batchNumber", "countedBy"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "product"
  },
  {
    key: "sales-quotations",
    title: "Quotation Management",
    subtitle: "Quotation creation, discount approval and conversion into sales orders.",
    entityName: "Quotation",
    route: "/app/sales/quotations",
    endpoint: "/api/sales/quotations",
    permission: "sales",
    fields: [commonText("quotationNo", "Quotation No"), commonText("customer", "Customer"), commonText("product", "Product"), money("quantity", "Quantity"), money("unitPrice", "Unit Price"), money("discountPercent", "Discount %"), { ...statusField, options: ["Draft", "Pending Approval", "Approved", "Rejected", "Converted"] }],
    tableColumns: ["quotationNo", "customer", "product", "quantity", "unitPrice", "discountPercent", "status"],
    searchable: ["quotationNo", "customer", "product"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "customer",
    printTemplate: "quotation"
  },
  {
    key: "sales-orders",
    title: "Sales Orders",
    subtitle: "Order confirmation, stock reservation and delivery workflow.",
    entityName: "Sales Order",
    route: "/app/sales/orders",
    endpoint: "/api/sales/orders",
    permission: "sales",
    fields: [commonText("orderNo", "Order No"), commonText("quotationNo", "Quotation No"), commonText("customer", "Customer"), commonText("product", "Product"), money("quantity", "Quantity"), money("amount", "Amount"), { ...statusField, options: ["Draft", "Sales Order", "Delivered", "Cancelled"] }],
    tableColumns: ["orderNo", "quotationNo", "customer", "product", "quantity", "amount", "status"],
    searchable: ["orderNo", "quotationNo", "customer", "product"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "customer"
  },
  {
    key: "sales-challans",
    title: "Delivery Challans",
    subtitle: "Delivery challan, vehicle, driver and delivery status tracking.",
    entityName: "Delivery Challan",
    route: "/app/sales/challans",
    endpoint: "/api/sales/challans",
    permission: "sales",
    fields: [commonText("challanNo", "Challan No"), commonText("orderNo", "Order No"), commonText("customer", "Customer"), date("deliveryDate", "Delivery Date"), commonText("vehicleNo", "Vehicle No"), { ...statusField, options: ["Draft", "Ready", "Delivered", "Cancelled"] }],
    tableColumns: ["challanNo", "orderNo", "customer", "deliveryDate", "vehicleNo", "status"],
    searchable: ["challanNo", "orderNo", "customer", "vehicleNo"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "customer",
    printTemplate: "challan"
  },
  {
    key: "sales-invoices",
    title: "Sales Invoices",
    subtitle: "Invoice posting, COGS, revenue, unit margin and total profit realized.",
    entityName: "Invoice",
    route: "/app/sales/invoices",
    endpoint: "/api/sales/invoices",
    permission: "sales",
    fields: [commonText("invoiceNo", "Invoice No"), date("salesDate", "Sales Date"), commonText("customerName", "Customer"), commonText("productName", "Product"), commonText("productCode", "Product Code"), money("unitLandedCost", "Unit Landed Cost"), money("qtySold", "Qty Sold"), money("unitSalePrice", "Unit Sale Price"), money("totalGrossRevenue", "Gross Revenue"), money("totalProfitRealized", "Profit"), { ...statusField, options: ["Draft", "Posted", "Cancelled"] }],
    tableColumns: ["invoiceNo", "salesDate", "customerName", "productName", "qtySold", "totalGrossRevenue", "totalProfitRealized", "status"],
    searchable: ["invoiceNo", "customerName", "productName", "productCode"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "customerName",
    printTemplate: "invoice"
  },
  {
    key: "sales-collections",
    title: "Collection Entries",
    subtitle: "Collection entry, receipt posting, method and customer dues control.",
    entityName: "Collection",
    route: "/app/sales/collections",
    endpoint: "/api/sales/collections",
    permission: "sales",
    fields: [commonText("receiptNo", "Receipt No"), commonText("invoiceNo", "Invoice No"), commonText("customer", "Customer"), date("collectionDate", "Collection Date"), money("amount", "Amount"), { key: "method", label: "Method", type: "select", required: true, options: ["Cash", "Bank", "Cheque", "MFS"] }, { ...statusField, options: ["Draft", "Pending Approval", "Posted", "Rejected"] }],
    tableColumns: ["receiptNo", "invoiceNo", "customer", "collectionDate", "amount", "method", "status"],
    searchable: ["receiptNo", "invoiceNo", "customer", "method"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "customer",
    printTemplate: "receipt"
  },
  {
    key: "sales-returns",
    title: "Sales Returns",
    subtitle: "Return requests, invoice linkage, product quantity, reason and approval workflow.",
    entityName: "Sales Return",
    route: "/app/sales/returns",
    endpoint: "/api/sales/returns",
    permission: "sales",
    fields: [commonText("returnNo", "Return No"), commonText("invoiceNo", "Invoice No"), commonText("customer", "Customer"), commonText("product", "Product"), money("quantity", "Quantity"), commonText("reason", "Reason"), { ...statusField, options: ["Draft", "Pending Approval", "Approved", "Rejected", "Posted"] }],
    tableColumns: ["returnNo", "invoiceNo", "customer", "product", "quantity", "reason", "status"],
    searchable: ["returnNo", "invoiceNo", "customer", "product", "reason"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "reason"
  },
  {
    key: "sales-visits",
    title: "Visit Logs",
    subtitle: "Field visit history, next follow-up date, remarks and GPS-ready sales activity tracking.",
    entityName: "Visit",
    route: "/app/sales/visits",
    endpoint: "/api/sales/visits",
    permission: "sales",
    fields: [
      date("visitDate", "Visit Date"),
      commonText("customer", "Customer"),
      commonText("outcome", "Outcome"),
      commonText("checkInTime", "Check-in Time"),
      { key: "gpsLat", label: "GPS Latitude", type: "number", required: true },
      { key: "gpsLng", label: "GPS Longitude", type: "number", required: true },
      { key: "accuracyMeter", label: "Accuracy Meter", type: "number", required: true },
      { key: "routeSequence", label: "Route Sequence", type: "number", required: true },
      date("nextFollowUp", "Next Follow-up"),
      { ...statusField, options: ["Planned", "Completed", "Missed", "Follow-up"] }
    ],
    tableColumns: ["visitDate", "customer", "checkInTime", "gpsLat", "gpsLng", "accuracyMeter", "status"],
    searchable: ["customer", "outcome", "status", "checkInTime"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "outcome"
  },
  {
    key: "sales-targets",
    title: "Targets & Commission",
    subtitle: "Sales target assignment by rep and territory with achievement and commission rate tracking.",
    entityName: "Sales Target",
    route: "/app/sales/targets",
    endpoint: "/api/sales/targets",
    permission: "sales",
    fields: [commonText("salesRep", "Sales Rep"), commonText("territory", "Territory"), money("monthlyTarget", "Monthly Target"), money("achieved", "Achieved"), money("commissionRate", "Commission Rate %"), { ...statusField, options: ["On Track", "Attention", "Achieved", "Missed"] }],
    tableColumns: ["salesRep", "territory", "monthlyTarget", "achieved", "commissionRate", "status"],
    searchable: ["salesRep", "territory", "status"],
    filterKey: "territory",
    statusKey: "status",
    descriptionKey: "territory"
  },
  {
    key: "accounts-vouchers",
    title: "Vouchers",
    subtitle: "Journal, contra, payment and receipt vouchers with posting workflow.",
    entityName: "Voucher",
    route: "/app/accounts/vouchers",
    endpoint: "/api/accounts/vouchers",
    permission: "accounts",
    fields: [commonText("voucherNo", "Voucher No"), { key: "type", label: "Type", type: "select", required: true, options: ["Journal", "Contra", "Payment", "Receipt"] }, commonText("party", "Party"), money("amount", "Amount"), date("date", "Date"), { ...statusField, options: ["Draft", "Pending Approval", "Approved", "Posted", "Rejected", "Cancelled"] }],
    tableColumns: ["voucherNo", "type", "party", "amount", "date", "status"],
    searchable: ["voucherNo", "type", "party"],
    filterKey: "type",
    statusKey: "status",
    descriptionKey: "party"
  },
  {
    key: "accounts-receivables",
    title: "Receivables",
    subtitle: "Customer aging, credit exposure and overdue collection control.",
    entityName: "Receivable",
    route: "/app/accounts/receivables",
    endpoint: "/api/accounts/receivables",
    permission: "accounts",
    fields: [commonText("customer", "Customer"), money("current", "Current"), money("days30", "30 Days"), money("days60", "60 Days"), money("days90", "90 Days"), money("totalDue", "Total Due"), { ...statusField, options: ["Normal", "Attention", "Hold"] }],
    tableColumns: ["customer", "current", "days30", "days60", "days90", "totalDue", "status"],
    searchable: ["customer", "status"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "customer"
  },
  {
    key: "accounts-payables",
    title: "Payables",
    subtitle: "Supplier dues, upcoming payments and bank position planning.",
    entityName: "Payable",
    route: "/app/accounts/payables",
    endpoint: "/api/accounts/payables",
    permission: "accounts",
    fields: [commonText("supplier", "Supplier"), date("dueDate", "Due Date"), money("amount", "Amount"), commonText("currency", "Currency"), { ...statusField, options: ["Scheduled", "Due", "Paid", "Hold"] }],
    tableColumns: ["supplier", "dueDate", "amount", "currency", "status"],
    searchable: ["supplier", "currency", "status"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "supplier"
  },
  {
    key: "accounts-cash-book",
    title: "Cash Book",
    subtitle: "Cash debit, credit and running balance ledger with posting status.",
    entityName: "Cash Entry",
    route: "/app/accounts/cash-book",
    endpoint: "/api/accounts/cash-book",
    permission: "accounts",
    fields: [date("date", "Date"), commonText("narration", "Narration"), money("debit", "Debit"), money("credit", "Credit"), money("balance", "Balance"), { ...statusField, options: ["Draft", "Posted", "Cancelled"] }],
    tableColumns: ["date", "narration", "debit", "credit", "balance", "status"],
    searchable: ["narration", "status"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "narration"
  },
  {
    key: "accounts-bank-book",
    title: "Bank Book",
    subtitle: "Bank transaction ledger, reconciliation status and active account balances.",
    entityName: "Bank Entry",
    route: "/app/accounts/bank-book",
    endpoint: "/api/accounts/bank-book",
    permission: "accounts",
    fields: [commonText("bank", "Bank"), commonText("accountNo", "Account No"), money("debit", "Debit"), money("credit", "Credit"), money("balance", "Balance"), { ...statusField, options: ["Reconciled", "Pending Reconciliation", "Posted", "Draft"] }],
    tableColumns: ["bank", "accountNo", "debit", "credit", "balance", "status"],
    searchable: ["bank", "accountNo", "status"],
    filterKey: "bank",
    statusKey: "status",
    descriptionKey: "accountNo"
  },
  {
    key: "accounts-general-ledger",
    title: "General Ledger",
    subtitle: "Chart-of-account movement with debit, credit, balance and posting status.",
    entityName: "Ledger Entry",
    route: "/app/accounts/general-ledger",
    endpoint: "/api/accounts/general-ledger",
    permission: "accounts",
    fields: [commonText("accountCode", "Account Code"), commonText("accountName", "Account Name"), money("debit", "Debit"), money("credit", "Credit"), money("balance", "Balance"), { ...statusField, options: ["Draft", "Posted", "Cancelled"] }],
    tableColumns: ["accountCode", "accountName", "debit", "credit", "balance", "status"],
    searchable: ["accountCode", "accountName", "status"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "accountName"
  },
  {
    key: "expenses",
    title: "Expense Management",
    subtitle: "Office rent, utilities, fuel, TA/DA, salary, marketing and department-wise expense allocation.",
    entityName: "Expense",
    route: "/app/expenses",
    endpoint: "/api/expenses",
    permission: "expenses",
    fields: [commonText("expenseNo", "Expense No"), { key: "category", label: "Category", type: "select", required: true, options: ["Office Rent", "Electricity", "Internet", "Fuel", "TA/DA", "Salary", "Bonus", "Marketing", "Entertainment", "Maintenance", "Other"] }, commonText("department", "Department"), money("amount", "Amount"), date("date", "Date"), { ...statusField, options: ["Draft", "Pending Approval", "Approved", "Rejected", "Posted"] }],
    tableColumns: ["expenseNo", "category", "department", "amount", "date", "status"],
    searchable: ["expenseNo", "category", "department"],
    filterKey: "category",
    statusKey: "status",
    descriptionKey: "department"
  },
  {
    key: "hr-employees",
    title: "Employee Master",
    subtitle: "Employee profile, department, designation, salary and employment status.",
    entityName: "Employee",
    route: "/app/hr/employees",
    endpoint: "/api/employees",
    permission: "hr",
    fields: [commonText("employeeName", "Employee Name"), commonText("department", "Department"), commonText("designation", "Designation"), money("salary", "Salary"), statusField],
    tableColumns: ["employeeName", "department", "designation", "salary", "status"],
    searchable: ["employeeName", "department", "designation"],
    filterKey: "department",
    statusKey: "status",
    descriptionKey: "designation"
  },
  {
    key: "hr-payroll",
    title: "Payroll Processing",
    subtitle: "Salary structure, bonus, deductions, net pay and payslip print view.",
    entityName: "Payslip",
    route: "/app/hr/payroll",
    endpoint: "/api/payroll",
    permission: "hr",
    fields: [commonText("payslipNo", "Payslip No"), commonText("employeeName", "Employee Name"), money("grossSalary", "Gross Salary"), money("bonus", "Bonus"), money("deductions", "Deductions"), money("netPay", "Net Pay"), { ...statusField, options: ["Draft", "Ready", "Posted"] }],
    tableColumns: ["payslipNo", "employeeName", "grossSalary", "bonus", "deductions", "netPay", "status"],
    searchable: ["payslipNo", "employeeName"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "employeeName",
    printTemplate: "payslip"
  },
  {
    key: "hr-attendance",
    title: "Attendance & Leave",
    subtitle: "Daily attendance, check-in/check-out status and HR review workflow.",
    entityName: "Attendance Entry",
    route: "/app/hr/attendance",
    endpoint: "/api/attendance",
    permission: "hr",
    fields: [commonText("employeeName", "Employee Name"), date("date", "Date"), commonText("checkIn", "Check In"), commonText("checkOut", "Check Out"), { ...statusField, options: ["Present", "Absent", "Late", "Leave", "Holiday"] }],
    tableColumns: ["employeeName", "date", "checkIn", "checkOut", "status"],
    searchable: ["employeeName", "date", "status"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "employeeName"
  },
  {
    key: "hr-leave-advances",
    title: "Leave, Advance & Loan",
    subtitle: "Leave applications, salary advance requests, loan placeholders and approval workflow.",
    entityName: "HR Request",
    route: "/app/hr/leave-advances",
    endpoint: "/api/hr/leave-advances",
    permission: "hr",
    fields: [commonText("employeeName", "Employee Name"), { key: "requestType", label: "Request Type", type: "select", required: true, options: ["Leave", "Salary Advance", "Employee Loan"] }, date("fromDate", "From Date"), date("toDate", "To Date"), money("amount", "Amount"), commonText("reason", "Reason"), { ...statusField, options: ["Draft", "Pending Approval", "Approved", "Rejected", "Posted"] }],
    tableColumns: ["employeeName", "requestType", "fromDate", "toDate", "amount", "status"],
    searchable: ["employeeName", "requestType", "reason", "status"],
    filterKey: "requestType",
    statusKey: "status",
    descriptionKey: "reason"
  },
  {
    key: "transport",
    title: "Transport Management",
    subtitle: "Vehicle, driver, trip, fuel, delivery cost allocation and maintenance scheduling.",
    entityName: "Trip",
    route: "/app/transport",
    endpoint: "/api/trips",
    permission: "transport",
    fields: [commonText("tripNo", "Trip No"), commonText("vehicleNo", "Vehicle No"), commonText("driver", "Driver"), commonText("customer", "Customer"), money("fuelCost", "Fuel Cost"), money("deliveryCost", "Delivery Cost"), { ...statusField, options: ["Scheduled", "Completed", "Cancelled", "Maintenance Due"] }],
    tableColumns: ["tripNo", "vehicleNo", "driver", "customer", "fuelCost", "deliveryCost", "status"],
    searchable: ["tripNo", "vehicleNo", "driver", "customer"],
    filterKey: "status",
    statusKey: "status",
    descriptionKey: "customer"
  }
];

export function getModuleConfigByRoute(pathname: string) {
  return moduleConfigs.find((config) => config.route === pathname);
}

export function getModuleConfigByKey(key: string) {
  return moduleConfigs.find((config) => config.key === key);
}
